# Generated by Django 4.2.3 on 2023-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='news', to='simpleapp.category'),
        ),
    ]
